### ISSUE TITLE
solve 167. Two Sum II - Input Array Is Sorted with Binary Search Algorithm

### ISSUE THREAD

**Issue by adilwahla** [adilwahla/my_leetcode_solutions#2]
**_I have already done this(check in repository code is available) with two-pointer Method So, please don't use Two-pointer Method The acceptable answer would be (log n) complexity_**  
### [167. Two Sum II - Input Array Is Sorted](https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/)
Given a 1-indexed array of integers numbers that is already sorted in non-decreasing order, find two numbers such that they add up to a specific target number. Let these two numbers be numbers[index1] and numbers[index2] where 1 <= index1 < index2 <= numbers.length.

Return the indices of the two numbers, index1 and index2, added by one as an integer array [index1, index2] of length 2.

The tests are generated such that there is exactly one solution. You may not use the same element twice.

Your solution must use only constant extra space.

 

**Example 1:**

```
Input: numbers = [2,7,11,15], target = 9
Output: [1,2]
Explanation: The sum of 2 and 7 is 9. Therefore, index1 = 1, index2 = 2. We return [1, 2].
```
**Example 2:**

```
Input: numbers = [2,3,4], target = 6
Output: [1,3]
Explanation: The sum of 2 and 4 is 6. Therefore index1 = 1, index2 = 3. We return [1, 3].
```
**Example 3:**
```

Input: numbers = [-1,0], target = -1
Output: [1,2]
Explanation: The sum of -1 and 0 is -1. Therefore index1 = 1, index2 = 2. We return [1, 2].
```
 

**Constraints:**

2 <= numbers.length <= 3 * 104
-1000 <= numbers[i] <= 1000
numbers is sorted in non-decreasing order.
-1000 <= target <= 1000
The tests are generated such that there is exactly one solution.

**Comment by PILOTEZEBS** [comment]
what is your concern right now please?

**Comment by adilwahla** [comment]
Hey thanks for your response, I want code with any algorithm but not linear search

**Comment by adilwahla** [comment]
@PILOTEZEBS open pull request once you coded are you coding?

**Comment by PILOTEZEBS** [comment]
ok wait i try to see this and then i give you a pul request
<img src="https://camo.githubusercontent.com/9c46d844bdce5ffadaf25778d2d81e25c45496d4ffc33872fa2852dbd822e154/68747470733a2f2f6d656469612e627261776c74696d652e6e696e6a612f627261776c6572732f7469636b2f70696e732f50696e2d4747416e696d2e6769663f73697a653d313630"/>

**Comment by PILOTEZEBS** [comment]
#3

**Comment by adilwahla** [comment]
I appreciate your effort the code was same as of mine though good effort still looking for better alternate solution closing for now

**Comment by PILOTEZEBS** [comment]
thankss
